'------------------------------------------------------------------------------
' <auto-generated>
'     이 코드는 도구를 사용하여 생성되었습니다.
'     런타임 버전:4.0.30319.42000
'
'     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
'     이러한 변경 내용이 손실됩니다.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    '클래스에서 자동으로 생성되었습니다.
    '멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    '다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    '''<summary>
    '''  지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ssaemtable.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        '''  속성을 재정의합니다.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property arrow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property b_arrow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("b_arrow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property b_bt_close() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("b_bt_close", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property b_bt_close2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("b_bt_close2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property b_bt_hide() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("b_bt_hide", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property b_bt_lock_false() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("b_bt_lock_false", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property b_bt_lock_true() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("b_bt_lock_true", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property b_bt_next() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("b_bt_next", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property b_bt_prev() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("b_bt_prev", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property b_bt_titleapply() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("b_bt_titleapply", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property b_bt_titleedit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("b_bt_titleedit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property b_bt_zoom1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("b_bt_zoom1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property b_bt_zoom2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("b_bt_zoom2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property b_bt1_table() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("b_bt1_table", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property b_bt1_table_old() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("b_bt1_table_old", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property b_bt2_opt() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("b_bt2_opt", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property b_bt3_opacity() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("b_bt3_opacity", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property b_divide() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("b_divide", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property b_edge() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("b_edge", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property bt_close() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bt_close", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property bt_close2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bt_close2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property bt_hide() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bt_hide", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property bt_lock_false() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bt_lock_false", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property bt_lock_true() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bt_lock_true", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property bt_next() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bt_next", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property bt_next1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bt_next1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property bt_prev() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bt_prev", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property bt_titleapply() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bt_titleapply", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property bt_titleedit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bt_titleedit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property bt_zoom1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bt_zoom1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property bt_zoom2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bt_zoom2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property bt1_table() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bt1_table", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property bt2_opt() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bt2_opt", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property bt3_opacity() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bt3_opacity", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property divide() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("divide", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property edge() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("edge", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  {\rtf1\ansi\ansicpg949\deff0\deflang1033\deflangfe1042{\fonttbl{\f0\fnil\fcharset129 \&apos;b8\&apos;bc\&apos;c0\&apos;ba \&apos;b0\&apos;ed\&apos;b5\&apos;f1;}{\f1\fnil\fcharset0 Arial;}{\f2\fswiss\fcharset0 Arial;}}
        '''{\colortbl ;\red192\green192\blue192;}
        '''\viewkind4\uc1\pard\cf1\lang1042\b\f0\fs29\&apos;b0\&apos;fa\&apos;b8\&apos;f1\&apos;b8\&apos;ed\cf0\b0\fs18\par
        '''\cf1\f1\fs24 1-11\cf0\f2\fs18\par
        '''\cf1\f0\&apos;c1\&apos;f8\&apos;b5\&apos;b5: 123\f1 p\cf0\f2\fs20\par
        '''}과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Friend ReadOnly Property EXMP_RTF() As String
            Get
                Return ResourceManager.GetString("EXMP_RTF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  {\rtf1\ansi\ansicpg949\deff0\deflang1033\deflangfe1042{\fonttbl{\f0\fnil\fcharset129 \&apos;b8\&apos;bc\&apos;c0\&apos;ba \&apos;b0\&apos;ed\&apos;b5\&apos;f1;}{\f1\fnil\fcharset0 Arial;}{\f2\fswiss\fcharset0 Arial;}}
        '''{\colortbl ;\red63\green63\blue63;}
        '''\viewkind4\uc1\pard\cf1\lang1042\b\f0\fs29\&apos;b0\&apos;fa\&apos;b8\&apos;f1\&apos;b8\&apos;ed\cf0\b0\fs18\par
        '''\cf1\f1\fs24 1-11\cf0\f2\fs18\par
        '''\cf1\f0\&apos;c1\&apos;f8\&apos;b5\&apos;b5: 123\f1 p\cf0\f2\fs20\par
        '''}과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Friend ReadOnly Property EXMP_RTF_BLACK() As String
            Get
                Return ResourceManager.GetString("EXMP_RTF_BLACK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property verpic() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("verpic", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  쌤테이블 Ssaemtable
        '''버전 beta 1028 릴리즈
        '''
        '''제작 21012박동준 © 2018 / 경북고컴동 (PBJSoftware)
        '''본 프로그램은 아직 한창 개발중입니다
        '''제작자 메일 pdj5096@gmail.com
        '''피드백 접수 페이지 http://fb.ssaemtable.kro.kr
        '''최신 버전 다운로드 링크 http://beta.ssaem.kro.kr과(와) 유사한 지역화된 문자열을 찾습니다.
        '''</summary>
        Friend ReadOnly Property VERTEXT() As String
            Get
                Return ResourceManager.GetString("VERTEXT", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
